[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
staking_pool = "6BgSHXAjvG37ZrugqxSgZ5nDJ9mAor5c3h3Vqb6E3p2h"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "mocha -r ts-node/register -t 1000000 tests/**/*.ts"
